name: Bug
description: Broken functionality or unexpected behaviour.
labels: [type: bug]
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Issue
      description: A brief description of the bug.
      placeholder: Describe what is happening.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Clear and concise instructions on how to reproduce the bug.
      placeholder: Provide steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.
      placeholder: What should have happened instead.
    validations:
      required: true