name: Maintenance
description: A general maintenance task.
labels: [type: maintenance]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the maintenance task.
      placeholder: Describe the maintenance task to be carried out.
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: The type of issue being addressed.
      options:
        - Maintenance
      default: 0
    validations:
      required: true